name: josko_assistant
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_blue: ^0.7.2
  flutter_launcher_icons: ^0.7.5
  weather_icons: ^2.0.1
  flutter_secure_storage: ^3.3.3
  speech_to_text: ^3.1.0
  material_design_icons_flutter: ^4.0.5345
  cupertino_icons: ^0.1.3
  http: ^0.13.4
  wifi_info_flutter: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true