-- MySQL Script generated by MySQL Workbench
-- čet 27 jan 2022 15:35:07
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA joskoDatabase DEFAULT CHARACTER SET utf8;
USE joskoDatabase;

-- -----------------------------------------------------
-- Table mydb.User
-- -----------------------------------------------------
CREATE TABLE User (
  UserID INT NOT NULL,
  Username VARCHAR(45) NOT NULL,
  Password VARCHAR(45) NOT NULL,
  PRIMARY KEY (UserID)
)ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table mydb.Type
-- -----------------------------------------------------
CREATE TABLE Type (
  TypeID INT NOT NULL,
  TypeName VARCHAR(45) NOT NULL,
  PRIMARY KEY (TypeID)
)ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table mydb.Task
-- -----------------------------------------------------
CREATE TABLE Task (
  TaskID INT NOT NULL,
  PinNum INT NOT NULL,
  TypeID INT NOT NULL,
  PRIMARY KEY (TaskID),
  INDEX fk_Task_Type_idx (TypeID ASC),
  CONSTRAINT fk_Task_Type
    FOREIGN KEY (TypeID)
    REFERENCES Type (TypeID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table mydb.User_has_Task
-- -----------------------------------------------------
CREATE TABLE User_has_Task (
  UserID INT NOT NULL,
  TaskID INT NOT NULL,
  PRIMARY KEY (UserID, TaskID),
  INDEX fk_User_has_Task_Task1_idx (TaskID ASC),
  INDEX fk_User_has_Task_User1_idx (UserID ASC),
  CONSTRAINT fk_User_has_Task_User1
    FOREIGN KEY (UserID)
    REFERENCES User (UserID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_User_has_Task_Task1
    FOREIGN KEY (TaskID)
    REFERENCES Task (TaskID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
